name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  music-service:
    name: Test Music Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r music-service/requirements.txt
      - name: Test with pytest
        env:
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
          UPLOADER_ID: ${{ secrets.UPLOADER_ID }}
          UPLOADER_NAME: ${{ secrets.UPLOADER_NAME }}
        run: |
          cd music-service
          pytest
  mobile-client:
    name: Test Mobile Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change into Flutter directory
        run: |
          cd mobile-client
      - name: Install dependencies
        uses: steebchen/flutter@v1.0.0
        with:
          args: pub get
      - name: Test
        uses: steebchen/flutter@v1.0.0
        with:
          args: test
